### ISSUE TITLE
Pydantic tied to 1.8.1

### ISSUE THREAD

**Issue by aaraney** [hydroshare/hsmodels#15]
Currently, `hsmodels` requires [`pydantic==1.8.1`](https://github.com/hydroshare/hsmodels/blob/e40254b2c9b0c293c2d6aa5dac7b5fb72dc1ce79/setup.py#L12). Is there a reason why this is the case? If not, it would be nice to allow versions higher than 1.8.1 for downstream user dependency resolution.

**Comment by sblack-usu** [comment]
That should be a 'pydantic>=1.8.1'

https://github.com/hydroshare/hsmodels/commit/48f385f206351971ee69a6202c6a4b16ee93fe90
